### PR TITLE
Update chp2 ros example

### PR DESCRIPTION
**Pull request by adipokala**
This PR contains updates to ROS examples of chapter 2 and its corresponding code.
Made sure the examples complies and executes.
Please, leave comment if any updates can be made.

### CODE REVIEW

**Comment by pablogh-2000** [comment]
Squash all commits into one.
I don't see an update on the readme.md with the installation instructions. Do they work exactly as explained in the readme? If not, please update the readme.
Please also add @tomasz3dk  to this PR as he needs to add ROS part of the tutorial to CI.

**Review by pablogh-2000 — COMMENTED** [review]
Squash all commits into one.
I don't see an update on the readme.md with the installation instructions. Do they work exactly as explained in the readme? If not, please update the readme.
Please also add @tomasz3dk to this PR as he needs to add ROS part of the tutorial to CI.

**Comment by adipokala** [comment]
> Changes in `.github/workflows/push.yml` are already in main branch, so they shouldn't be visible here. Looks like you didn't rebase your branch on top of main branch and do squash in right way.

What can I do to make it right?

**Comment by mharshe** [comment]
> > Changes in `.github/workflows/push.yml` are already in main branch, so they shouldn't be visible here. Looks like you didn't rebase your branch on top of main branch and do squash in right way.
> 
> What can I do to make it right?

Assuming you have already checked out this branch:
```
git pull orgin
git rebase origin/main update-chp2-ros-example
```
then verify that when you do  `git diff origin/main` you should not see any changes to the push.yml file.

**Review by pablogh-2000 — APPROVED** [review]

**Review by mharshe — APPROVED** [review]

**Pull request merged**
